//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources.DTO.v1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Competition {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Competition() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Resources.DTO.v1.Competition", typeof(Competition).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About organising.
        /// </summary>
        public static string AboutOrganising {
            get {
                return ResourceManager.GetString("AboutOrganising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitions.
        /// </summary>
        public static string Competitions {
            get {
                return ResourceManager.GetString("Competitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitions organised by me.
        /// </summary>
        public static string CompetitionsOrganisedByMe {
            get {
                return ResourceManager.GetString("CompetitionsOrganisedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In which country is it taking place?.
        /// </summary>
        public static string CountryId {
            get {
                return ResourceManager.GetString("CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -If the competition is going to take place just for one day you can leave the end date empty.
        /// </summary>
        public static string DateInfo {
            get {
                return ResourceManager.GetString("DateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string DBCompetition {
            get {
                return ResourceManager.GetString("DBCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Everything else please add to comments: the exact place, entry fees, maximum amout on players per team etc..
        /// </summary>
        public static string ElseInfo {
            get {
                return ResourceManager.GetString("ElseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Competitions.
        /// </summary>
        public static string MyCompetitions {
            get {
                return ResourceManager.GetString("MyCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed, you are not the organiser of that competition!.
        /// </summary>
        public static string NotOrganiser {
            get {
                return ResourceManager.GetString("NotOrganiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiser.
        /// </summary>
        public static string Organiser {
            get {
                return ResourceManager.GetString("Organiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -If you are the organiser then just put your fullname into organiser.
        /// </summary>
        public static string OrganiserInfo {
            get {
                return ResourceManager.GetString("OrganiserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participations.
        /// </summary>
        public static string Participations {
            get {
                return ResourceManager.GetString("Participations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting after:.
        /// </summary>
        public static string StartingAfter {
            get {
                return ResourceManager.GetString("StartingAfter", resourceCulture);
            }
        }
    }
}
