//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources.DTO.v1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompetitionTeam {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompetitionTeam() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Resources.DTO.v1.CompetitionTeam", typeof(CompetitionTeam).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All teams at competitions.
        /// </summary>
        public static string AllTeamsAtCompetitions {
            get {
                return ResourceManager.GetString("AllTeamsAtCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team is already registered to the competition!.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition name.
        /// </summary>
        public static string CompetitionId {
            get {
                return ResourceManager.GetString("CompetitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition teams.
        /// </summary>
        public static string CompetitionTeams {
            get {
                return ResourceManager.GetString("CompetitionTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team at Competition.
        /// </summary>
        public static string DBCompetitionTeam {
            get {
                return ResourceManager.GetString("DBCompetitionTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My teams at competitions.
        /// </summary>
        public static string MyTeamsAtCompetitions {
            get {
                return ResourceManager.GetString("MyTeamsAtCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date registered.
        /// </summary>
        public static string RegisteredAt {
            get {
                return ResourceManager.GetString("RegisteredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to competition.
        /// </summary>
        public static string RegisterToCompetition {
            get {
                return ResourceManager.GetString("RegisterToCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        public static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort competitions by country.
        /// </summary>
        public static string SortByCountry {
            get {
                return ResourceManager.GetString("SortByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this team from this competition?.
        /// </summary>
        public static string SureRemove {
            get {
                return ResourceManager.GetString("SureRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string TeamId {
            get {
                return ResourceManager.GetString("TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams attending my competitions.
        /// </summary>
        public static string TeamsAttendingMyCompetitions {
            get {
                return ResourceManager.GetString("TeamsAttendingMyCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams attending this competition.
        /// </summary>
        public static string TeamsAttendingThisCompetition {
            get {
                return ResourceManager.GetString("TeamsAttendingThisCompetition", resourceCulture);
            }
        }
    }
}
