//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources.DTO.v1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Game {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Game() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Resources.DTO.v1.Game", typeof(Game).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add game.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All games.
        /// </summary>
        public static string AdminGames {
            get {
                return ResourceManager.GetString("AdminGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team.
        /// </summary>
        public static string AwayId {
            get {
                return ResourceManager.GetString("AwayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away score.
        /// </summary>
        public static string AwayScore {
            get {
                return ResourceManager.GetString("AwayScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string DbGame {
            get {
                return ResourceManager.GetString("DbGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Extra time half length is required..
        /// </summary>
        public static string ExtraTimeError {
            get {
                return ResourceManager.GetString("ExtraTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra time half length (min).
        /// </summary>
        public static string ExtraTimeHalfLength {
            get {
                return ResourceManager.GetString("ExtraTimeHalfLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game type.
        /// </summary>
        public static string GameTypeId {
            get {
                return ResourceManager.GetString("GameTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half length (min).
        /// </summary>
        public static string HalfLength {
            get {
                return ResourceManager.GetString("HalfLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team.
        /// </summary>
        public static string HomeId {
            get {
                return ResourceManager.GetString("HomeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home score.
        /// </summary>
        public static string HomeScore {
            get {
                return ResourceManager.GetString("HomeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you did not choose game type to be &quot;Two halves&quot;.
        /// </summary>
        public static string IfExtraTimeOrPenalties {
            get {
                return ResourceManager.GetString("IfExtraTimeOrPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kickoff time.
        /// </summary>
        public static string KickOffTime {
            get {
                return ResourceManager.GetString("KickOffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games from my competitions.
        /// </summary>
        public static string OrganiserGames {
            get {
                return ResourceManager.GetString("OrganiserGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this game?.
        /// </summary>
        public static string SureDeleteThis {
            get {
                return ResourceManager.GetString("SureDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My teams at games.
        /// </summary>
        public static string TeamManagerGames {
            get {
                return ResourceManager.GetString("TeamManagerGames", resourceCulture);
            }
        }
    }
}
